const type=document.body.dataset.type||'plant';
const info={plant:{name:'Tế bào thực vật',hint:'Ghép 20 mảnh để nhận ra màng tế bào, tế bào chất, nhân và một vài cấu trúc đặc trưng.'},animal:{name:'Tế bào động vật',hint:'Ghép 20 mảnh để nhận ra màng tế bào, tế bào chất và nhân. Không cần nhớ chi tiết.'},prokaryotic:{name:'Tế bào nhân sơ',hint:'Ghép 20 mảnh để nhận ra màng tế bào, tế bào chất và vùng chứa vật chất di truyền. Không có nhân hoàn chỉnh.'}}[type];
document.title='Game ghép hình – '+info.name;document.querySelector('#title').textContent=info.name;document.querySelector('#hint').textContent=info.hint;
const canvas=document.createElement('canvas');canvas.width=440;canvas.height=352;const c=canvas.getContext('2d');
function grad(a,b){const g=c.createLinearGradient(0,0,440,352);g.addColorStop(0,a);g.addColorStop(1,b);return g}function label(t,x,y,s=14){c.fillStyle='#17324d';c.font='bold '+s+'px Arial';c.fillText(t,x,y)}
function plant(){c.fillStyle=grad('#c8f2ba','#4cae61');c.beginPath();c.roundRect(8,8,424,336,48);c.fill();c.strokeStyle='#2e7d32';c.lineWidth=8;c.stroke();c.fillStyle=grad('#f5ffd8','#a7e58e');c.beginPath();c.roundRect(25,25,390,302,38);c.fill();c.strokeStyle='#54a83d';c.lineWidth=5;c.stroke();c.fillStyle='rgba(255,255,255,.35)';c.beginPath();c.ellipse(225,178,150,112,0,0,Math.PI*2);c.fill();c.fillStyle=grad('#f4a6d1','#b95c9d');c.beginPath();c.ellipse(225,180,62,58,0,0,Math.PI*2);c.fill();label('NHÂN',190,185);c.fillStyle='#ffe48c';c.beginPath();c.ellipse(130,120,68,42,0,0,Math.PI*2);c.fill();label('KHÔNG BÀO',88,125,11);[[85,235],[350,110],[345,250],[105,75]].forEach(([x,y])=>{c.fillStyle='#55b85b';c.beginPath();c.ellipse(x,y,35,15,.3,0,Math.PI*2);c.fill();c.fillStyle='#2e7d32';c.beginPath();c.ellipse(x,y,20,7,.3,0,Math.PI*2);c.fill()});label('MÀNG TẾ BÀO',155,315);label('TẾ BÀO CHẤT',18,55,13)}
function animal(){c.fillStyle=grad('#ffd5ee','#d98be8');c.beginPath();c.ellipse(220,176,195,150,0,0,Math.PI*2);c.fill();c.strokeStyle='#8e44ad';c.lineWidth=8;c.stroke();c.fillStyle='rgba(255,255,255,.38)';c.beginPath();c.ellipse(220,176,170,128,0,0,Math.PI*2);c.fill();c.fillStyle=grad('#a967dc','#7040a6');c.beginPath();c.ellipse(220,176,65,62,0,0,Math.PI*2);c.fill();label('NHÂN',190,181);label('MÀNG TẾ BÀO',140,315);label('TẾ BÀO CHẤT',18,55,13);for(let i=0;i<9;i++){let x=75+(i*43)%300,y=90+(i*67)%190;c.fillStyle='#fff4a8';c.beginPath();c.arc(x,y,7,0,Math.PI*2);c.fill()}}
function prok(){c.fillStyle=grad('#ffe7a6','#f4a23c');c.beginPath();c.roundRect(18,60,404,232,116);c.fill();c.strokeStyle='#d96b12';c.lineWidth=9;c.stroke();c.fillStyle='rgba(255,255,255,.28)';c.beginPath();c.roundRect(34,76,372,200,100);c.fill();c.strokeStyle='#ffd27a';c.lineWidth=5;c.stroke();c.strokeStyle='#9b3eaa';c.lineWidth=7;c.beginPath();c.ellipse(220,175,82,55,.2,0,Math.PI*2);c.stroke();c.beginPath();c.ellipse(220,175,45,30,-.5,0,Math.PI*2);c.stroke();label('VÙNG ADN',175,180);label('MÀNG TẾ BÀO',145,315);label('TẾ BÀO CHẤT',18,55,13);for(let i=0;i<18;i++){let x=55+(i*71)%330,y=95+(i*37)%165;c.fillStyle='#d65b5b';c.beginPath();c.arc(x,y,4,0,Math.PI*2);c.fill()}}
if(type==='plant')plant();else if(type==='animal')animal();else prok();const image=canvas.toDataURL('image/png');
const target=document.querySelector('.target');for(let i=0;i<20;i++){const s=document.createElement('div');s.className='slot';s.dataset.i=i;target.appendChild(s)}const board=document.querySelector('.board'),pieces=[],W=88,H=88;
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function placeRandom(el){const r=board.getBoundingClientRect();el.style.left=(Math.random()*(r.width-W-20)+10)+'px';el.style.top=(Math.random()*(r.height-H-20)+10)+'px'}
function makePiece(i){const el=document.createElement('div');el.className='piece';el.dataset.i=i;const col=i%5,row=Math.floor(i/5);el.style.backgroundImage=`url(${image})`;el.style.backgroundPosition=`-${col*W}px -${row*H}px`;placeRandom(el);board.appendChild(el);pieces.push(el);let moving=false,ox=0,oy=0;el.addEventListener('pointerdown',e=>{if(el.dataset.locked)return;moving=true;el.classList.add('drag');el.setPointerCapture(e.pointerId);const b=el.getBoundingClientRect();ox=e.clientX-b.left;oy=e.clientY-b.top});el.addEventListener('pointermove',e=>{if(!moving)return;const p=board.getBoundingClientRect();el.style.left=(e.clientX-p.left-ox)+'px';el.style.top=(e.clientY-p.top-oy)+'px'});el.addEventListener('pointerup',()=>{moving=false;el.classList.remove('drag');snap(el)})}
function snap(el){const i=+el.dataset.i,s=target.children[i],a=el.getBoundingClientRect(),b=s.getBoundingClientRect(),d=Math.hypot(a.left+a.width/2-b.left-b.width/2,a.top+a.height/2-b.top-b.height/2);if(d<55){const br=board.getBoundingClientRect(),tr=s.getBoundingClientRect();el.style.left=(tr.left-br.left)+'px';el.style.top=(tr.top-br.top)+'px';el.dataset.locked='1';el.style.zIndex=2;s.classList.add('ok');if(pieces.every(p=>p.dataset.locked)){document.querySelector('.success').classList.add('show');document.querySelector('#count').textContent='20/20'}}}
shuffle([...Array(20).keys()]).forEach(makePiece);document.querySelector('#count').textContent='0/20';document.querySelector('#restart').onclick=()=>location.reload();