const type=document.body.dataset.type||'plant';
const info={plant:{hint:'Quan sát hình sau khi ghép xong và đoán đây là loại tế bào nào.'},animal:{hint:'Quan sát hình sau khi ghép xong và đoán đây là loại tế bào nào.'},prokaryotic:{hint:'Quan sát hình sau khi ghép xong và đoán đây là loại tế bào nào.'}}[type];
document.title='Game ghép hình tế bào KHTN 6';document.querySelector('#hint').textContent=info.hint;
const canvas=document.createElement('canvas');canvas.width=480;canvas.height=360;const c=canvas.getContext('2d');
function grad(a,b){const g=c.createLinearGradient(0,0,480,360);g.addColorStop(0,a);g.addColorStop(1,b);return g}
function plant(){c.fillStyle=grad('#b9efb5','#55a85d');c.beginPath();c.roundRect(12,12,456,336,48);c.fill();c.strokeStyle='#2f7838';c.lineWidth=9;c.stroke();c.fillStyle=grad('#f2ffd5','#a9e48d');c.beginPath();c.roundRect(32,32,416,296,38);c.fill();c.strokeStyle='#4d9d48';c.lineWidth=5;c.stroke();c.fillStyle='rgba(255,255,255,.32)';c.beginPath();c.ellipse(255,180,145,105,0,0,Math.PI*2);c.fill();c.fillStyle=grad('#f5afd4','#a95a9b');c.beginPath();c.ellipse(180,185,58,54,0,0,Math.PI*2);c.fill();c.strokeStyle='#7b3d75';c.lineWidth=5;c.stroke();c.fillStyle='#70436f';c.beginPath();c.arc(180,185,18,0,Math.PI*2);c.fill();c.fillStyle='#8dd7ef';c.strokeStyle='#4d9db6';c.lineWidth=5;c.beginPath();c.ellipse(305,190,105,70,0,0,Math.PI*2);c.fill();c.stroke();[[80,95],[365,95],[390,250],[90,260],[280,75],[300,285]].forEach(([x,y],i)=>{c.save();c.translate(x,y);c.rotate(i%2?.25:-.18);c.fillStyle='#4caa57';c.strokeStyle='#2c7438';c.lineWidth=4;c.beginPath();c.ellipse(0,0,34,17,0,0,Math.PI*2);c.fill();c.stroke();c.strokeStyle='#b9e88e';c.lineWidth=2;for(let k=-16;k<=16;k+=8){c.beginPath();c.moveTo(k,-9);c.lineTo(k,9);c.stroke()}c.restore()})}
function animal(){c.fillStyle=grad('#ffd8ef','#c67bdc');c.beginPath();c.ellipse(240,180,215,150,0,0,Math.PI*2);c.fill();c.strokeStyle='#81449d';c.lineWidth=9;c.stroke();c.fillStyle='rgba(255,255,255,.34)';c.beginPath();c.ellipse(240,180,190,128,0,0,Math.PI*2);c.fill();c.fillStyle=grad('#a96bdf','#7040a4');c.beginPath();c.ellipse(215,180,65,60,0,0,Math.PI*2);c.fill();c.strokeStyle='#5a3486';c.lineWidth=5;c.stroke();c.fillStyle='#5d3485';c.beginPath();c.arc(215,180,18,0,Math.PI*2);c.fill();[[90,115],[350,110],[115,245],[345,255],[275,80],[280,285]].forEach(([x,y])=>{c.fillStyle='#e98d57';c.strokeStyle='#a95732';c.lineWidth=3;c.beginPath();c.ellipse(x,y,28,14,.2,0,Math.PI*2);c.fill();c.stroke();c.strokeStyle='#ffd3a8';c.lineWidth=2;c.beginPath();c.moveTo(x-16,y);c.bezierCurveTo(x-5,y-8,x,y+8,x+8,y);c.bezierCurveTo(x+16,y-8,x+18,y+6,x+22,y-2);c.stroke()});for(let i=0;i<18;i++){let x=70+(i*83)%340,y=75+(i*61)%220;c.fillStyle='#f5c95c';c.beginPath();c.arc(x,y,4,0,Math.PI*2);c.fill()}}
function prokaryotic(){c.fillStyle=grad('#ffe9a9','#f1a43e');c.beginPath();c.roundRect(22,65,436,230,115);c.fill();c.strokeStyle='#cf6814';c.lineWidth=10;c.stroke();c.fillStyle='rgba(255,255,255,.3)';c.beginPath();c.roundRect(40,82,400,196,95);c.fill();c.strokeStyle='#f6c86b';c.lineWidth=5;c.stroke();c.strokeStyle='#9a3fa0';c.lineWidth=8;c.beginPath();c.ellipse(240,180,90,58,.15,0,Math.PI*2);c.stroke();c.beginPath();c.ellipse(240,180,48,30,-.45,0,Math.PI*2);c.stroke();for(let i=0;i<22;i++){let x=60+(i*71)%360,y=105+(i*43)%155;c.fillStyle='#c95151';c.beginPath();c.arc(x,y,4,0,Math.PI*2);c.fill()}c.strokeStyle='#6e55a5';c.lineWidth=4;c.beginPath();c.moveTo(35,130);c.bezierCurveTo(0,90,10,50,45,45);c.stroke();c.beginPath();c.moveTo(445,235);c.bezierCurveTo(480,270,475,320,435,325);c.stroke()}
if(type==='plant')plant();else if(type==='animal')animal();else prokaryotic();
const image=canvas.toDataURL('image/png');const COLS=6,ROWS=3,N=18,W=80,H=120;const target=document.querySelector('.target');for(let i=0;i<N;i++){const s=document.createElement('div');s.className='slot';s.dataset.i=i;target.appendChild(s)}const board=document.querySelector('.board');let pieces=[],selected=null,moves=0;
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function placeRandom(el){const r=board.getBoundingClientRect();el.style.left=Math.max(8,Math.random()*(r.width-W-16))+'px';el.style.top=Math.max(8,Math.random()*(r.height-H-16))+'px'}
function makePiece(i){const el=document.createElement('div');el.className='piece';el.dataset.i=i;const col=i%COLS,row=Math.floor(i/COLS);el.style.width=W+'px';el.style.height=H+'px';el.style.backgroundImage=`url(${image})`;el.style.backgroundSize=(COLS*W)+'px '+(ROWS*H)+'px';el.style.backgroundPosition=`-${col*W}px -${row*H}px`;placeRandom(el);board.appendChild(el);pieces.push(el);el.addEventListener('click',()=>{if(el.dataset.locked)return;if(selected===null){selected=el;el.classList.add('selected')}else if(selected===el){el.classList.remove('selected');selected=null}else swapPieces(selected,el)});let moving=false,ox=0,oy=0;el.addEventListener('pointerdown',e=>{if(el.dataset.locked)return;moving=true;el.classList.add('drag');el.setPointerCapture(e.pointerId);const b=el.getBoundingClientRect();ox=e.clientX-b.left;oy=e.clientY-b.top});el.addEventListener('pointermove',e=>{if(!moving)return;const r=board.getBoundingClientRect();el.style.left=(e.clientX-r.left-ox)+'px';el.style.top=(e.clientY-r.top-oy)+'px'});el.addEventListener('pointerup',()=>{if(!moving)return;moving=false;el.classList.remove('drag');snap(el)});return el}
function snap(el){const i=+el.dataset.i,s=target.children[i],a=el.getBoundingClientRect(),b=s.getBoundingClientRect(),d=Math.hypot(a.left+a.width/2-b.left-b.width/2,a.top+a.height/2-b.top-b.height/2);if(d<58){const r=board.getBoundingClientRect(),q=s.getBoundingClientRect();el.style.left=(q.left-r.left)+'px';el.style.top=(q.top-r.top)+'px';el.dataset.locked='1';el.style.zIndex=2;s.classList.add('ok');checkWin()}}
function swapPieces(a,b){if(a===b)return;moves++;const al=a.style.left,at=a.style.top,bl=b.style.left,bt=b.style.top;a.style.left=bl;a.style.top=bt;b.style.left=al;b.style.top=at;a.classList.remove('selected');b.classList.remove('selected');selected=null;document.querySelector('#moves').textContent=moves}
function checkWin(){if(pieces.every(p=>p.dataset.locked)){document.querySelector('.success').classList.add('show');document.querySelector('#count').textContent='18/18'}}function resetGame(){board.querySelectorAll('.piece').forEach(x=>x.remove());pieces=[];selected=null;moves=0;document.querySelector('#moves').textContent='0';document.querySelector('#count').textContent='0/18';shuffle([...Array(N).keys()]).forEach(makePiece)}resetGame();document.querySelector('#restart').onclick=resetGame;